apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reusable patch to inject baseline environment variables into the deployment container
patches:
  - target:
      kind: Deployment
      name: whoami
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENVIRONMENT
            value: "placeholder"
          - name: APP_VERSION
            value: "v1.5.0"
